# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pig' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pig
  pod 'Firebase/Analytics'
  pod 'Fabric', '~> 1.10.2'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Crashlytics', '~> 3.13.4' 
  
  target 'pigTests' do
    inherit! :search_paths
   
  end

end
